// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwmmlrctbojsvoykfpug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13bW1scmN0Ym9qc3ZveWtmcHVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwOTQ2MzgsImV4cCI6MjA2MTY3MDYzOH0.tfMZOBHUTA-5DAoF0tYpfeuF8h1c00i8oxNFBtPivUM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);